### ISSUE TITLE
--opt-threshold --scf-threshold arguments dont work with xtb

### ISSUE THREAD

**Issue by manufmwhite** [anooplab/PyAR#12]
When trying to apply loose --opt-threshold --scf-threshold, vtight is used instead. 
pyar.log show "Command '['xtb', 'trial_000_001_ag_a_006.xyz', '-opt', 'vtight']' " despite the fact I did "pyar-cli -a A.xyz -N 10 -m 2 -as 10 --software xtb --opt-threshold loose --scf-threshold loose".

**Comment by anooplab** [comment]
It is included for xtb now for opt-threshold.

**Comment by manufmwhite** [comment]
Now i have an error when running "pyar-cli -a A.xyz -N 10 -m 2 -as 10 --software xtb --opt-threshold loose"
It outputs:
Traceback (most recent call last):
  File "/usr/local/bin/pyar-cli", line 425, in <module>
    main()
  File "/usr/local/bin/pyar-cli", line 332, in main
    aggregator.aggregate(seeds, size_of_aggregate,
  File "/usr/local/lib/python3.8/dist-packages/pyar/aggregator.py", line 149, in aggregate
    seed_storage[ag_id] = add_one(ag_id,
  File "/usr/local/lib/python3.8/dist-packages/pyar/aggregator.py", line 325, in add_one
    status_list = [optimise(each_mol, qc_params) for each_mol in
  File "/usr/local/lib/python3.8/dist-packages/pyar/aggregator.py", line 325, in <listcomp>
    status_list = [optimise(each_mol, qc_params) for each_mol in
  File "/usr/local/lib/python3.8/dist-packages/pyar/optimiser.py", line 51, in optimise
    geometry = xtb.Xtb(molecule, qc_params)
  File "/usr/local/lib/python3.8/dist-packages/pyar/interface/xtb.py", line 41, in __init__
    self.cmd = f"xtb {self.start_xyz_file} -opt {options['opt_threshold']}"
NameError: name 'options' is not defined

**Comment by anooplab** [comment]
Oops! changed but forgot to push.  It works for me now.
